name: Build and Deploy to OVH VPS

# Déclencher le workflow sur les push vers la branche main
on:
  push:
    branches:
      - main
    # Pour optimiser, ne déclencher que sur les changements pertinents
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/**'
  # Permettre de lancer manuellement le workflow depuis l'interface GitHub
  workflow_dispatch:

env:
  # Version de l'image avec date pour le traçage
  IMAGE_VERSION: ${{ github.sha }}
  # Utiliser l'utilisateur debian du VPS
  VPS_USER: debian

jobs:
  deploy:
    name: Deploy to OVH VPS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Create archive of repository
        run: |
          # Vérifier que rsync est installé
          if ! command -v rsync &> /dev/null; then
            echo "Installation de rsync..."
            sudo apt-get update && sudo apt-get install -y rsync
          fi
          
          # Créer un répertoire temporaire et y copier les fichiers pour éviter les erreurs de fichiers modifiés
          echo "Création de l'archive pour le déploiement..."
          TEMP_DIR=$(mktemp -d)
          rsync -a --quiet --exclude='.git' --exclude='node_modules' --exclude='.github' . "$TEMP_DIR"
          cd "$TEMP_DIR"
          tar -czf "$GITHUB_WORKSPACE/harmoneyz-deploy.tar.gz" .
          cd "$GITHUB_WORKSPACE"
          rm -rf "$TEMP_DIR"
          echo "Archive créée avec succès:"
          ls -lah harmoneyz-deploy.tar.gz

      - name: Copy files to VPS and deploy
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
        run: |
          # Copier l'archive vers le VPS
          echo "Transfert de l'archive vers le VPS..."
          scp -o ConnectTimeout=30 harmoneyz-deploy.tar.gz $VPS_USER@${{ secrets.VPS_HOST }}:~/
          
          # Vérifier que le transfert a réussi
          if [ $? -ne 0 ]; then
            echo "Erreur lors du transfert de l'archive vers le VPS."
            exit 1
          fi

          # Exécuter le script de déploiement sur le VPS
          echo "Lancement du déploiement sur le VPS..."
          ssh -o ConnectTimeout=30 $VPS_USER@${{ secrets.VPS_HOST }} << 'EOF'
            set -e  # Arrêter le script en cas d'erreur
            
            # En cas d'erreur, nettoyer et sortir
            cleanup() {
              echo "Une erreur s'est produite. Nettoyage..."
              [ -f ~/harmoneyz-deploy.tar.gz ] && rm ~/harmoneyz-deploy.tar.gz
              exit 1
            }
            
            trap cleanup ERR
            
            # Créer répertoire de déploiement s'il n'existe pas
            echo "Préparation du répertoire de déploiement..."
            mkdir -p ~/harmoneyz
            cd ~/harmoneyz
            
            # Extraire les fichiers de l'archive
            echo "Extraction des fichiers..."
            tar -xzf ~/harmoneyz-deploy.tar.gz
            
            # Nettoyer l'archive après extraction
            rm ~/harmoneyz-deploy.tar.gz
            
            # Vérifier quelle version de Docker est disponible
            if ! command -v docker &> /dev/null; then
              echo "Docker n'est pas installé. Installation impossible depuis ce script."
              exit 1
            fi
            
            # Vérifier et ajouter les permissions Docker si nécessaire
            if ! groups | grep -q docker; then
              echo "L'utilisateur actuel n'est pas dans le groupe docker."
              echo "Exécution de docker avec sudo..."
              DOCKER_CMD="sudo docker"
              COMPOSE_PREFIX="sudo"
            else
              echo "L'utilisateur actuel est dans le groupe docker."
              DOCKER_CMD="docker"
              COMPOSE_PREFIX=""
            fi
            
            # Construire l'image Docker localement
            echo "Construction de l'image Docker..."
            $DOCKER_CMD build -t harmoneyz:latest . || {
              echo "Erreur lors de la construction de l'image Docker."
              exit 1
            }
            
            # Création/mise à jour du fichier docker-compose.yml
            echo "Configuration de docker-compose.yml..."
            cat > docker-compose.yml << 'EOCF'
            version: '3.8'
            
            services:
              harmoneyz:
                image: harmoneyz:latest
                restart: always
                healthcheck:
                  test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
                  interval: 30s
                  timeout: 10s
                  retries: 3
                  start_period: 10s
                ports:
                  - "80:80"
                # Limiter les ressources
                deploy:
                  resources:
                    limits:
                      cpus: '0.5'
                      memory: 512M
                logging:
                  driver: "json-file"
                  options:
                    max-size: "10m"
                    max-file: "3"
            EOCF
            
            # Déterminer quelle version de Docker Compose utiliser
            echo "Détection de Docker Compose..."
            if command -v docker compose &> /dev/null; then
              # Docker Compose V2
              echo "Utilisation de Docker Compose V2"
              COMPOSE_CMD="${COMPOSE_PREFIX} docker compose"
            elif command -v docker-compose &> /dev/null; then
              # Docker Compose V1
              echo "Utilisation de Docker Compose V1"
              COMPOSE_CMD="${COMPOSE_PREFIX} docker-compose"
            else
              # Installation de Docker Compose
              echo "Installation de Docker Compose..."
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
              COMPOSE_CMD="${COMPOSE_PREFIX} docker-compose"
            fi
            
            # Arrêter les conteneurs existants
            echo "Arrêt des conteneurs existants..."
            $COMPOSE_CMD down || true
            
            # Démarrer les nouveaux conteneurs
            echo "Démarrage des nouveaux conteneurs..."
            $COMPOSE_CMD up -d
            
            # Vérifier que le déploiement a réussi
            echo "Vérification du déploiement..."
            sleep 10  # Attendre un peu plus longtemps pour que le conteneur démarre complètement
            if ! $COMPOSE_CMD ps | grep -q "Up"; then
              echo "Le déploiement a échoué. Vérifiez les logs:"
              $COMPOSE_CMD logs
              exit 1
            fi
            
            # Afficher les informations sur les conteneurs en cours d'exécution
            echo "✅ Déploiement terminé avec succès!"
            $COMPOSE_CMD ps
            
            # Nettoyer les images Docker inutilisées
            echo "Nettoyage des images Docker inutilisées..."
            $DOCKER_CMD image prune -af --filter "until=24h" || true
            
            # Afficher l'espace disque disponible
            echo "Espace disque restant:"
            df -h /
          EOF 